### ISSUE TITLE
Making the image on the about page smaller

### ISSUE THREAD

**Issue by MarcoMorawec** [tfletcher0516/Splurty#3]
Note: This is purely optional and I'm not sure if you intended to make your about page look this way.

Right now your image on the about page is really large and takes up the full width of the column. I suggest you make the image smaller so you have your image and text be next to each other - take a look at the wireframes in lesson 3 to visualize what I'm referring to.

This is what I'm seeing right now:

![screen shot 2015-05-24 at 9 19 40 am](https://cloud.githubusercontent.com/assets/1474717/7787995/6e3a8f70-01f6-11e5-8bb4-de804861fc37.png)

**Comment by tfletcher0516** [comment]
This was another typo issue. Fixed.
