### ISSUE TITLE
Fixing the Modal

### ISSUE THREAD

**Issue by MarcoMorawec** [tfletcher0516/Splurty#4]
Currently the font of the modal headline looks a bit too big, which makes the sentence wrap into two lines. By making the font just a bit smaller things would look a lot more aligned.

Sidenote: you have some strange characters in the top right corner of the modal, instead of the "X" to close the modal. I'd recommend looking into that as well :)

Here's what I'm seeing:

![screen shot 2015-05-24 at 9 24 08 am](https://cloud.githubusercontent.com/assets/1474717/7788002/f8590be6-01f6-11e5-8417-0cdc8f45a36f.png)

**Comment by tfletcher0516** [comment]
Font adjusted. X works. I had a space where there should not have been one.

**Comment by MarcoMorawec** [comment]
@tfletcher0516 :+1:
